
services:
  frontend:
    image: 'legal-ai-frontend:latest'
    networks:
      - default
    restart: always
    ports:
      - "5173:5173"
    build:
      context: frontend
      dockerfile: Dockerfile

  backend:
    image: 'legal-ai-backend:latest'
    networks:
      - default
    restart: always
    ports:
      - "80:80"
    build:
      context: backend
      dockerfile: Dockerfile
