
services:
  frontend:
    image: 'legal-ai-frontend:latest'
    restart: always
    ports:
      - "5173:5173"
    build:
      context: frontend
      dockerfile: Dockerfile
    env_file:
      - .env

  backend:
    image: 'legal-ai-backend:latest'
    restart: always
    ports:
      - "8082:80"
    env_file:
      - .env
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./storage:/app/storage
      - ./emb_model:/app/emb_model