name: Publish to production server

on:
  push:
    branches:
      - cicd

jobs:
  deploy:
    runs-on: production
    steps:
      - name: Create .env file
        run: echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
      - name: Run Docker Compose
        run: docker compose up -d --build
